(#65) updated documentation
cake-contrib/Cake.Chocolatey.Module pull request #70
Opened 2024-08-06 09:07 UTC by nils-a

## Description

* Changed wording in some places.
* updated the "Setup" section to reflect the current Cake version
* updated the layout to reflect what is being used in other cake-contrib addins/modules (GitHub link and link to discussions in the lower right)

## Related Issue

fixes #65 

## Motivation and Context

#65

## How Has This Been Tested?

manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Documentation

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-08-06 13:04 UTC, gep13 requested changes
Just a couple small things, otherwise, these changes look great! Thanks for getting this done!

2024-08-06 13:04 UTC, gep13 commented on docs/input/docs/usage/configuration.md
>  https://chocolatey.org/api/v2/
Depending on the outcome of our other conversation, this might need to change as well.

2024-08-06 13:04 UTC, gep13 commented on docs/input/docs/usage/examples.md
> +See [the chocolatey setup](https://docs.chocolatey.org/en-us/choco/setup/#non-administrative-install) for more information.
```suggestion
See [the Chocolatey CLI setup](https://docs.chocolatey.org/en-us/choco/setup/#non-administrative-install) for more information.

```

2024-08-06 13:04 UTC, gep13 commented on docs/input/docs/installation/Setup.md
> +1. Add the following line in you're cake.recipe:
Would/should this be build.cake?  Or if you are pointing at Cake.Recipe being used, recipe.cake?

```suggestion
1. Add the following line in you're build.cake:

```

2024-08-06 14:02 UTC, nils-a commented on docs/input/docs/usage/configuration.md
>  https://chocolatey.org/api/v2/
Agreed. However, I would rather leave it as-is, for this PR and create a new issue to fix the default source.

2024-10-17 09:10 UTC, gep13 approved these changes
LGTM!

2024-10-17 09:10 UTC, merged

2024-10-17 09:11 UTC, gep13 commented
@nils-a Thank you very much for getting this fixed up, and apologies on not getting back to you sooner on this!